name: cloudy_app
description: "Minimalist Weather App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2
  geolocator: ^13.0.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter_native_splash:
  color: "#42a5f5"
  #background_image: "assets/background.png"

  # Following are specific parameters for Android 12+.
  android_12:
  #image: assets/android12splash.png
  # Splash screen background color.
  #color: "#42a5f5"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900